[LOOP-5035] Pump event time zone sync
tidepool-org/TidepoolService pull request #107
Opened 2024-09-20 19:08 UTC by nhamming

https://tidepool.atlassian.net/browse/LOOP-5035

2024-09-20 19:18 UTC, Camji55 approved these changes

2024-09-20 20:23 UTC, darinkrauss requested changes
Just one change...

2024-09-20 20:23 UTC, darinkrauss commented on TidepoolServiceKit/Extensions/PersistedPumpEvent.swift
> +        datum = datum.adornWith(id: datumId(for: userId, type: TStatusDeviceEventDatum.self),
The `TStatusDeviceEventDatum` needs to be replaced with `TTimeChangeDeviceEventDatum`, I believe.

2024-09-21 20:24 UTC, ps2 approved these changes
LGTM! Once Darin's request is completed.

2024-09-23 08:59 UTC, nhamming commented on TidepoolServiceKit/Extensions/PersistedPumpEvent.swift
> +        datum = datum.adornWith(id: datumId(for: userId, type: TStatusDeviceEventDatum.self),
good catch!

2024-09-23 15:26 UTC, darinkrauss approved these changes
LGTM!

2024-09-23 16:38 UTC, merged