LOOP-1479: Implement first 2 screens of prescription flow + mock manager
tidepool-org/TidepoolService pull request #11
Opened 2020-06-25 22:48 UTC by novalegra

- https://tidepool.atlassian.net/browse/LOOP-1479

- Create Prescription data model
- Create a mock prescription manager
- Create a UICoordinator to navigate between views in the flow
- Add button to TidepoolService setup view controller to trigger the onboarding flow
- Create assets folder with the Tidepool color palate and Dexcom/Dash images
- Create view model for initial part of flow
- Create the first 2 screens of the onboarding flow (prescription code entry & device review)
    - These are hosted in a `DismissibleHostingController` to prevent accidental dismissal, per discussions with design
    - Because the `TextField` keyboard in the code entry screen may cover the field on smaller devices, I added a struct to keep track of the keyboard height and provide appropriate amounts of padding to keep the field in view

2020-06-26 16:01 UTC, ps2 requested changes
Looks really good!  I think there are a couple of cleanup items that should be tackled, but otherwise this looks like a good first stab at implementing the prescription flow.

2020-06-26 16:01 UTC, ps2 commented on TidepoolServiceKit/Extensions/Prescription.swift
> +public enum CGMType: String, Codable {
Structs that represent objects within the Tidepool data model should be implemented in TidepoolKit. I think backend side of things isn't really in place for this, and this PR doesn't actually use the prescription yet, so maybe this can just be a mock (with a name to mark it as such).

2020-06-26 16:01 UTC, ps2 commented on TidepoolServiceKit/Mocks/MockPrescriptionManager.swift
> +extension TimeInterval {
The pattern for these is to put it into its own file in `Extensions`

2020-06-26 16:01 UTC, ps2 commented on TidepoolServiceKitUI/Views/PrescriptionCodeEntryView.swift
> +            .foregroundColor(purple)
The use of tidepool purple will be done at a higher level via `accentColor`. So your code doesn't need to worry about this for now. This line can be removed, and it will be the right color later when accentColor is overridden at a higher level.

2020-06-26 16:09 UTC, novalegra commented on TidepoolServiceKitUI/Views/PrescriptionCodeEntryView.swift
> +            .foregroundColor(purple)
Should all references to the purple be changed to `accentColor`?

2020-06-26 16:15 UTC, ps2 commented on TidepoolServiceKitUI/Views/PrescriptionCodeEntryView.swift
> +            .foregroundColor(purple)
Any places where you would expect the standard accentColor in DIY should use accentColor explicitly, or implicitly if that is already the default (as is the case with buttons and some other elements)

 Only things that are explicitly Tidepool branded and we'd expect them to keep that color even if used in DIY should use the purple color.

2020-06-26 16:55 UTC, ps2 approved these changes
LGTM! Would appreciate @darinkrauss taking a look before merge, though.

2020-06-26 17:10 UTC, rickpasetto commented
@novalegra @ps2 I will need to utilize the Dexcom and Dash icons for my work.  Would it make sense to put them into LoopKitUI?

2020-06-26 17:15 UTC, ps2 commented
@rickpasetto Yours should come from the actual PumpManagers.  Ideally Anna's should too, but we're not implementing device choosing in setup flow for v1, so I think just hardcoding them for now is fine.

2020-06-26 17:28 UTC, darinkrauss approved these changes
Looking great! 🚀 

Please don't be alarmed at the number of nits as they are more a reflection of my particular-ness than anything else (and I add them to most all PRs 😄). Just consider them suggestions for your consideration. Feel free to ignore any or all of the nits. 

Otherwise, I don't see a thing other than the nits, so LGTM! 🏎️

2020-06-26 17:28 UTC, darinkrauss commented on TidepoolServiceKit/Extensions/Prescription.swift
> +public enum CGMType: String, Codable {
:+1:

2020-06-26 17:28 UTC, darinkrauss commented on TidepoolServiceKit/Extensions/Prescription.swift
> +//
[nit] This isn't really an extension.

2020-06-26 17:28 UTC, darinkrauss commented on TidepoolServiceKit/Extensions/TimeInterval.swift
> +}
[nit] Consider copy/paste this implementation from LoopKit:
```
    static func minutes(_ minutes: Double) -> TimeInterval {
        return self.init(minutes: minutes)
    }

    static func hours(_ hours: Double) -> TimeInterval {
        return self.init(hours: hours)
    }

    init(minutes: Double) {
        self.init(minutes * 60)
    }

    init(hours: Double) {
        self.init(minutes: hours * 60)
    }
```

2020-06-26 17:28 UTC, darinkrauss commented on TidepoolServiceKit/Mocks/MockPrescription.swift
> +    public let bloodGlucoseUnit: HKUnit // CGM type (manufacturer & model)
I know this object is a mock, but something similar will end up in TidepoolKit (using many of the types already implemented in TidepoolKit). Consider dropping use of `HKUnit` and just use another enum. This would allow you to drop the custom `Codable` implementation below. The enum could have a func/var that converts it into an `HKUnit` if you'd like.

2020-06-26 17:28 UTC, darinkrauss commented on TidepoolServiceKit/Mocks/MockPrescriptionManager.swift
> +                    dailyItems: [RepeatingScheduleValue(startTime: .hours(0), value: DoubleRange(minValue: 100.0, maxValue: 110.0)), RepeatingScheduleValue(startTime: .hours(8), value: DoubleRange(mi
[nit] Consider breaking up into multiple lines as you did for the rest of this initializer.

2020-06-26 17:28 UTC, darinkrauss commented on TidepoolServiceKit/Mocks/MockPrescriptionManager.swift
> +                                                        start: Date().addingTimeInterval(-.minutes(30)),
[nit] Consider `.minutes(-30)`. For me, it is easy to miss the `-` prefix in front of the `.minutes(30)`.

2020-06-26 17:28 UTC, darinkrauss commented on TidepoolServiceKit/Mocks/MockPrescriptionManager.swift
> +
[nit] Extra blank line?

2020-06-26 17:28 UTC, darinkrauss commented on TidepoolServiceKit/TidepoolService.swift
> +        #if targetEnvironment(simulator)
[nit] With this you won't be able to demonstrate it on an official CircleCI build (or have design/product play with it). Consider just using the mock data for both simulator and non-simulator for now.

2020-06-26 17:28 UTC, darinkrauss commented on TidepoolServiceKitUI/TidepoolServiceSetupViewController.swift
> +        navigationItem.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .action, target: self, action: #selector(startFlow))
Is this just a way to "hop over" actually logging in for now?

2020-06-26 17:28 UTC, darinkrauss commented on TidepoolServiceKitUI/TidepoolServiceSetupViewController.swift
> +    let setupViewController = PrescriptionReviewUICoordinator()
[nit] Any reason why this needs to be define here as opposed to just creating it within `startFlow`?

2020-06-26 17:28 UTC, darinkrauss commented on TidepoolServiceKitUI/Views/PrescriptionDeviceView.swift
> +            Text(LocalizedString("Edit devices", comment:"Button title for editing the prescribed devices"))
[nit] Space after `comment:`?

2020-06-26 17:28 UTC, darinkrauss commented on TidepoolServiceKitUI/Views/PrescriptionDeviceView.swift
> +
[nit] Unnecessary whitespace?

2020-06-26 17:28 UTC, darinkrauss commented on TidepoolServiceKitUI/Views/PrescriptionDeviceView.swift
> +        .padding(5) // align with Dexcom
[nit] This seems fragile and we'll want to consider a more generic solution as we add different devices (so they all align correctly regardless of the size of the icon).

2020-06-26 17:28 UTC, darinkrauss commented on TidepoolServiceKitUI/Views/PrescriptionDeviceView.swift
> +
[nit] Extra whitespace? (I'm going to stop commenting on these since I figure you get the point. 😀 )

2020-06-26 17:28 UTC, darinkrauss commented on TidepoolServiceKitUI/Views/PrescriptionDeviceView.swift
> +                Text(LocalizedString("Omnipod 5", comment: "Text describing insulin pump name"))
[nit] `5`? Or is this just a placeholder?

2020-06-26 17:28 UTC, darinkrauss commented on TidepoolServiceKitUI/Views/PrescriptionDeviceView.swift
> +}
Did you want a preview here?

2020-06-26 17:28 UTC, darinkrauss commented on TidepoolServiceKitUI/Views/PrescriptionCodeEntryView.swift
> +        if enabled {
[nit] Consider `enabled ? .primary : .secondary`?

2020-06-26 17:28 UTC, darinkrauss commented on TidepoolServiceKitUI/Views/PrescriptionCodeEntryView.swift
> +                    LocalizedString("Prescription activation code", comment: "Label text for the first needed prescription activation item"),
[nit] Consider indenting elements within array?

2020-06-26 17:28 UTC, darinkrauss commented on TidepoolServiceKitUI/View Models/PrescriptionCodeEntryViewModel.swift
> +//  PrescriptionCodeEntryModel.swift
[nit] PrescriptionCodeEntryViewModel?

2020-06-26 17:28 UTC, darinkrauss commented on TidepoolServiceKitUI/View Models/PrescriptionCodeEntryViewModel.swift
> +           // Handle error
[nit] `TODO` so it doesn't get missed?

2020-06-26 17:28 UTC, darinkrauss commented on TidepoolServiceKitUI/View Models/PrescriptionCodeEntryViewModel.swift
> +    func validateCode(prescriptionCode: String) -> Bool {
[nit] Consider how this reads "validate code prescription code". Perhaps `validatePrescriptionCode(_ prescriptionCode: String)`? Same for function below.

2020-06-26 17:28 UTC, darinkrauss commented on TidepoolServiceKitUI/View Models/PrescriptionCodeEntryModel.swift
> +        #if targetEnvironment(simulator)
[nit] Consider just using Mock for simulator and non-simulator. After all, once TidepoolKit implements the backend API call we won't want the simulator to return a mock anymore.

2020-06-26 17:28 UTC, darinkrauss commented on TidepoolServiceKitUI/View Controllers/PrescriptionReviewUICoordinator.swift
> +    var completionDelegate: CompletionDelegate?
[nit] `weak`? Since the delegate is assigned to `self` below, won't this cause a retain cycle? Maybe not, but I generally assume all delegates should be `weak` to avoid the issue altogether.

2020-06-26 17:28 UTC, darinkrauss commented on TidepoolServiceKitUI/View Controllers/PrescriptionReviewUICoordinator.swift
> +        screenStack = [determineFirstScreen()]
[nit] Will the first screen every vary?

2020-06-26 17:49 UTC, novalegra commented on TidepoolServiceKit/Mocks/MockPrescription.swift
> +    public let bloodGlucoseUnit: HKUnit // CGM type (manufacturer & model)
This is a great suggestion, thanks!

2020-06-26 18:24 UTC, novalegra commented on TidepoolServiceKitUI/TidepoolServiceSetupViewController.swift
> +        navigationItem.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .action, target: self, action: #selector(startFlow))
This is intended to be a way to reliably (and quickly) trigger the prescriptions flow for demo purposes, since the rest of the onboarding is TBD. This won't stay here long-term

2020-06-26 18:27 UTC, novalegra commented on TidepoolServiceKitUI/TidepoolServiceSetupViewController.swift
> +    let setupViewController = PrescriptionReviewUICoordinator()
Fixed, we thought we were having issues with it going out of scope but that doesn't seem to be the case once I fixed the root issue

2020-06-26 19:06 UTC, novalegra commented on TidepoolServiceKitUI/Views/PrescriptionDeviceView.swift
> +        .padding(5) // align with Dexcom
Definitely agree. I took a look at the ways to do this with SwiftUI, and all the solutions aren't great, but I implemented the one that seemed the least-hacky

2020-06-26 19:06 UTC, novalegra commented on TidepoolServiceKitUI/View Controllers/PrescriptionReviewUICoordinator.swift
> +        screenStack = [determineFirstScreen()]
Yes, we'll eventually be keeping track of progress within the flow in the case the screen quit

2020-06-26 19:09 UTC, novalegra commented on TidepoolServiceKitUI/Views/PrescriptionDeviceView.swift
> +                Text(LocalizedString("Omnipod 5", comment: "Text describing insulin pump name"))
That was in the design I was given, I'm (hoping) it's a placeholder

2020-06-26 19:11 UTC, novalegra commented on TidepoolServiceKitUI/Views/PrescriptionDeviceView.swift
> +}
I honestly couldn't get the preview to work, and Rick had similar problems

2020-06-26 19:14 UTC, novalegra commented on TidepoolServiceKitUI/View Controllers/PrescriptionReviewUICoordinator.swift
> +    var completionDelegate: CompletionDelegate?
Thanks!

2020-06-29 19:23 UTC, rickpasetto commented on TidepoolServiceKit/Extensions/TimeInterval.swift
> +}
@darinkrauss doesn't `TidepoolService` have `LoopKit` as a dependency?  Just curious...should she just make those `LoopKit` functions public and then use them?

2020-06-29 19:23 UTC, rickpasetto commented on TidepoolServiceKitUI/Views/PrescriptionDeviceView.swift
> +    private var dashStack: some View {
Won't these icons and descriptions be vended from the device managers?  Or is this just placeholder until that's in place?

2020-06-29 19:23 UTC, rickpasetto commented on TidepoolServiceKitUI/Views/PrescriptionDeviceView.swift
> +            if let width = widths.max() {
I'm curious...what does this do?

2020-06-29 19:23 UTC, rickpasetto commented on TidepoolServiceKitUI/Views/PrescriptionDeviceView.swift
> +        .padding(5) // align with Dexcom
Hm...the way I did this in my screen was to fix the width of the image:

```swift
fileprivate struct LargeButton: View {
    
    let image: String
    let label: String
    let description: String

    static let spacing: CGFloat = 15
    static let imageWidth: CGFloat = 48
    static let topBottomPadding: CGFloat = 20
    
    public var body: some View {
        return HStack(spacing: Self.spacing) {
            Image(frameworkImage: image, decorative: true)
                .frame(width: Self.imageWidth)
            VStack(alignment: .leading) {
                Text(label)
                DescriptiveText(label: description)
            }
        }
        .padding(EdgeInsets(top: Self.topBottomPadding, leading: 0, bottom: Self.topBottomPadding, trailing: 0))
    }
}
```
Looks like this: 
<img width="370" alt="Screen Shot 2020-06-26 at 1 08 06 PM" src="https://user-images.githubusercontent.com/308993/85896866-1acc2380-b7ae-11ea-9a3d-b1ee676517f3.png">

2020-06-29 19:36 UTC, novalegra commented on TidepoolServiceKitUI/Views/PrescriptionDeviceView.swift
> +    private var dashStack: some View {
This is a placeholder. The icons/descriptions would need to be static in order for this screen to be able to access them - @rickpasetto do you know if that's the case at the moment?

2020-06-29 19:36 UTC, novalegra commented on TidepoolServiceKitUI/Views/PrescriptionDeviceView.swift
> +            if let width = widths.max() {
It aligns the images based on the max width

2020-06-29 19:57 UTC, rickpasetto commented on TidepoolServiceKit/Extensions/TimeInterval.swift
> +    public static func minutes(_ minutes: Double) -> TimeInterval {
@novalegra why not use the existing LoopKit functions for this?

2020-06-29 20:01 UTC, ps2 commented on TidepoolServiceKit/Extensions/TimeInterval.swift
> +    public static func minutes(_ minutes: Double) -> TimeInterval {
@rickpasetto We typically don't publicly export extensions to system types from our Frameworks.  There are exceptions, but these are likely conflict sources; imagine if another framework did the same. I could easily see another framework thinking "wouldn't it be nice to implement minute/hour/day extensions for TimeInterval and export them for everyone?".

2020-06-29 22:16 UTC, rickpasetto commented on TidepoolServiceKitUI/Views/PrescriptionDeviceView.swift
> +    private var dashStack: some View {
I am working on the ability to vend these images from the device managers.  My recommendation is to put `TODO` comments in the code for both the device "buttons" (image, title, and description) and say that they are static placeholders for now

2020-06-29 22:19 UTC, rickpasetto commented on TidepoolServiceKit/Extensions/TimeInterval.swift
> +    public static func minutes(_ minutes: Double) -> TimeInterval {
@ps2 I see.  @novalegra in that case, it is fine to leave these as-is.

2020-06-29 22:36 UTC, ps2 commented on TidepoolServiceKitUI/Views/PrescriptionDeviceView.swift
> +    private var dashStack: some View {
The device managers already do vend images for this use: https://github.com/tidepool-org/LoopKit/blob/dev/LoopKitUI/PumpManagerUI.swift#L18

2020-06-29 22:36 UTC, merged

2020-06-29 22:38 UTC, ps2 commented on TidepoolServiceKitUI/Views/PrescriptionDeviceView.swift
> +    private var dashStack: some View {
But this PR should hardcode them for now. We have no mechanism for a Service plugin to access currently available device managers, and we don't need to as initially we are going to be not allowing device selection during onboarding.

2020-06-29 22:40 UTC, rickpasetto commented on TidepoolServiceKitUI/Views/PrescriptionDeviceView.swift
> +    private var dashStack: some View {
@ps2 yes, but not before the devices are set up (in other words: as a static var instead of a member var).  I'm working on changing that now.