LOOP-1488: add delivery limits information screen + editors
tidepool-org/TidepoolService pull request #16
Opened 2020-07-15 14:02 UTC by novalegra

https://tidepool.atlassian.net/browse/LOOP-1488

2020-07-15 14:03 UTC, novalegra commented on TidepoolServiceKitUI/Views/DeliveryLimitsReviewView.swift
> +            // TODO: don't hard-code this value
How to address this problem will be discussed at dev sync tomorrow; I will update this before I merge based on that discussion

2020-07-15 17:33 UTC, mpangburn approved these changes
LGTM!

2020-07-15 17:33 UTC, mpangburn commented on TidepoolServiceKitUI/View Models/PrescriptionReviewViewModel.swift
> +        settings.maximumBasalRatePerHour = limits.maximumBasalRate?.doubleValue(for: HKUnit.internationalUnit().unitDivided(by: .hour()))
[nit] `.unitsPerHour`

2020-07-15 17:33 UTC, mpangburn commented on TidepoolServiceKitUI/View Controllers/PrescriptionReviewUICoordinator.swift
> +            }
[non-blocking] Should it even be possible to get here without a prescription? I'm realizing this check is duplicated at each step, and I wonder if we can enforce this in the type system by requiring a non-optional prescription after the initial step. Something to think about.

2020-07-15 22:16 UTC, novalegra commented on TidepoolServiceKitUI/View Controllers/PrescriptionReviewUICoordinator.swift
> -            guard let prescription = viewModel.prescription else {
We no longer need this because the data is guaranteed to be in the `settingsViewModel`

2020-07-15 22:17 UTC, novalegra commented on TidepoolServiceKitUI/View Models/PrescriptionReviewViewModel.swift
> -    }
Moved to `TherapySettingsViewModel`

2020-07-15 22:18 UTC, novalegra commented on TidepoolServiceKitUI/View Controllers/PrescriptionReviewUICoordinator.swift
> +            }
Removed :)

2020-07-15 23:26 UTC, rickpasetto requested changes
I have some minor requests for change, especially around defaulting the glucoseUnit when it is `nil`.  Please consider, then ping me when ready.  Thanks, and good job!

2020-07-15 23:26 UTC, rickpasetto commented on TidepoolServiceKitUI/Views/CorrectionRangeReviewView.swift
> +            unit: viewModel.therapySettings.glucoseUnit ?? .milligramsPerDeciliter,
Is defaulting to `.mmiligramsPerDeciliter` safe here?  Seems like this should be handled elsewhere...

2020-07-15 23:26 UTC, rickpasetto commented on TidepoolServiceKitUI/Views/CorrectionRangeOverrideReview.swift
> +        self.unit = model.therapySettings.glucoseUnit ?? .milligramsPerDeciliter
Fallback to `.milligramsPerDeciliter` seems odd here.  Seems to me you shouldn't get to this screen unless `model.therapySettings.glucoseUnit` is non-nil.  If it is `nil`, it is a programming error, right?  Should we consider

```
precondition(model.therapySettings.glucoseUnit != nil)
```
?

2020-07-15 23:26 UTC, rickpasetto commented on TidepoolServiceKitUI/Views/SuspendThresholdReview.swift
> +        self.unit = model.therapySettings.glucoseUnit ?? .milligramsPerDeciliter
See my comment above about fallback to `.milligramsPerDeciliter`

2020-07-15 23:26 UTC, rickpasetto commented on TidepoolServiceKitUI/Views/CorrectionRangeOverrideReview.swift
> +                }
[nit] consider just:
```suggestion
                self.viewModel.didFinishStep?()
```

2020-07-15 23:26 UTC, rickpasetto commented on TidepoolServiceKitUI/Views/CorrectionRangeReviewView.swift
> +                }
[nit] consider just:
```swift
    self.viewModel.didFinishStep?()
```

2020-07-15 23:26 UTC, rickpasetto commented on TidepoolServiceKitUI/Views/SuspendThresholdReview.swift
> +                }
[nit] consider just:
```swift
    self.viewModel.didFinishStep?()
```

2020-07-16 00:06 UTC, novalegra commented on TidepoolServiceKitUI/Views/CorrectionRangeOverrideReview.swift
> +        self.unit = model.therapySettings.glucoseUnit ?? .milligramsPerDeciliter
Yep, that sounds great! Thanks!

2020-07-16 00:12 UTC, novalegra commented on TidepoolServiceKitUI/View Controllers/PrescriptionReviewUICoordinator.swift
>              hostedView.title = LocalizedString("Temporary Ranges", comment: "Title for temporary correction range informational screen") // TODO: make this title be "Temporary Correction Ranges" when
@rickpasetto What should we do about the temporary correction range title? Here, if it's "Temporary Correction Ranges", then you run into the ellipses issue; I can leave the TODO in there and incorporate the enum you made when there's a fix for multi-line titles, but I'm not sure what makes the most sense from an architecture perspective

2020-07-16 17:05 UTC, rickpasetto commented on TidepoolServiceKitUI/View Controllers/PrescriptionReviewUICoordinator.swift
>              hostedView.title = LocalizedString("Temporary Ranges", comment: "Title for temporary correction range informational screen") // TODO: make this title be "Temporary Correction Ranges" when
Yeah let's not block this PR on this, and let's follow up later.

2020-07-16 17:09 UTC, rickpasetto approved these changes
LGTM!  nice job. 👍

2020-07-16 18:35 UTC, merged