LOOP-1515: update prescription code entry screen
tidepool-org/TidepoolService pull request #42
Opened 2020-08-13 22:00 UTC by novalegra

https://tidepool.atlassian.net/browse/LOOP-1515

2020-08-13 22:01 UTC, novalegra commented on TidepoolServiceKitUI/View Models/PrescriptionReviewViewModel.swift
> +        return prescriptionCode.count == prescriptionCodeLength && birthday.timeIntervalSinceReferenceDate > 0
This means that any entry will be accepted where:
1. prescription code is 6 chars
2. birthday is on/after Jan 1, 2001

2020-08-13 22:03 UTC, novalegra commented on TidepoolServiceKitUI/Views/PrescriptionCodeEntryView.swift
> +        ExpandableDatePicker(
Created 'custom' date picker because the current SwiftUI one doesn't expand properly if it's not in a Form (which we can't do here)

2020-08-13 22:03 UTC, novalegra commented on TidepoolServiceKitUI/Views/PrescriptionCodeEntryView.swift
>      private var requestPrescriptionButton: some View {
Left button in for whenever we return to this, as it's already properly styled

2020-08-13 22:04 UTC, novalegra commented on TidepoolServiceKitUI/Views/PrescriptionDeviceView.swift
> +        .frame(width: Self.imageWidth, height: 50)
Prevents "expansion" issue with the VStack spacing change

2020-08-14 15:40 UTC, nhamming approved these changes
Couple of questions, but otherwise LGTM.

2020-08-14 15:40 UTC, nhamming commented on TidepoolServiceKitUI/View Models/PrescriptionReviewViewModel.swift
> +    let placeholderFieldText = "MM/DD/YYYY"
Is this format really needed instead of user preference?

2020-08-14 15:40 UTC, nhamming commented on TidepoolServiceKitUI/View Models/PrescriptionReviewViewModel.swift
> +        return prescriptionCode.count == prescriptionCodeLength && birthday.timeIntervalSinceReferenceDate > 0
Hm... this was probably already considered, but putting a birthday into a code seems like a HIPAA violation.

2020-08-14 16:26 UTC, novalegra commented on TidepoolServiceKitUI/View Models/PrescriptionReviewViewModel.swift
> +        return prescriptionCode.count == prescriptionCodeLength && birthday.timeIntervalSinceReferenceDate > 0
From the discussions I've seen, the code is associated with a birthday, but the code isn't generated based on the birthday. Since we display a generic error in the case either the birthday or the code is incorrect, there isn't a way to associate a code with a birthday unless they're both correct

2020-08-14 16:31 UTC, novalegra commented on TidepoolServiceKitUI/View Models/PrescriptionReviewViewModel.swift
> +    let placeholderFieldText = "MM/DD/YYYY"
Changed to be "Select birthdate"

2020-08-14 16:38 UTC, nhamming approved these changes
LGTM

2020-08-14 16:38 UTC, nhamming commented on TidepoolServiceKitUI/View Models/PrescriptionReviewViewModel.swift
> +        return prescriptionCode.count == prescriptionCodeLength && birthday.timeIntervalSinceReferenceDate > 0
Ah... got it. Thanks.

2020-08-17 18:26 UTC, rickpasetto requested changes
Other than the Jan 1 2001 problem, looks ok to me.

2020-08-17 18:26 UTC, rickpasetto commented on TidepoolServiceKitUI/View Models/PrescriptionReviewViewModel.swift
> +        return prescriptionCode.count == prescriptionCodeLength && birthday.timeIntervalSinceReferenceDate > 0
+1 on the Jan 1, 2001 issue (I verified this is a bug).  Did you mean this to be
```suggestion
        return prescriptionCode.count == prescriptionCodeLength && validDateRange.contains(birthday)
```
?

2020-08-17 18:26 UTC, rickpasetto commented on TidepoolServiceKitUI/Views/PrescriptionCodeEntryView.swift
> +        ExpandableDatePicker(
Interesting...didn't know that.  I'm not well-versed enough in SwiftUI to confirm that but I buy it :).

2020-08-17 18:26 UTC, rickpasetto commented on TidepoolServiceKitUI/Views/PrescriptionCodeEntryView.swift
> +    // Default to 35 years ago for birthdays, which is what the Apple Health app does
Interesting.  I wonder how they picked that age?

2020-08-17 18:33 UTC, novalegra commented on TidepoolServiceKitUI/Views/PrescriptionCodeEntryView.swift
> +    // Default to 35 years ago for birthdays, which is what the Apple Health app does
I'm guessing because it's because it's in the middle of a typical age range (0-70), so it minimizes the amount of scrolling

2020-08-17 19:38 UTC, rickpasetto requested changes
One more minor fix?

2020-08-17 19:38 UTC, rickpasetto commented on TidepoolServiceKitUI/Views/PrescriptionCodeEntryView.swift
> +        return prescriptionCode.count == viewModel.prescriptionCodeLength
Hm...shouldn't this also only return true if there's a birthday (i.e. if the user taps on the picker at least once?)

2020-08-17 21:02 UTC, novalegra commented on TidepoolServiceKitUI/Views/PrescriptionCodeEntryView.swift
> +        return prescriptionCode.count == viewModel.prescriptionCodeLength
Yes, thanks! I was just talking with Brooke about this and will fix that

2020-08-17 22:02 UTC, rickpasetto reviewed
Had a comment and suggestion for improvement/simplification.  WDYT?

2020-08-17 22:02 UTC, rickpasetto commented on TidepoolServiceKitUI/Views/PrescriptionCodeEntryView.swift
> +    @State private var didTapOnPicker: Bool = false
Sorry if I'm being so picky here...but this strategy sort of surprised me.  I would have expected that you'd use `birthday` to indicate whether the button should be enabled (i.e. start it out as `nil`, and then enable the button when it is non-nil), instead of exposing the "didTap" state of the Picker.  After all...tapping on the picker isn't what makes the button valid...it's having a valid date chosen.  Do you agree?  Seems fewer moving parts to me.

2020-08-17 22:08 UTC, novalegra commented on TidepoolServiceKitUI/Views/PrescriptionCodeEntryView.swift
> +    @State private var didTapOnPicker: Bool = false
That's what I tried to do originally when I was creating the `ExpandableDatePicker`, but I ran into the issue that dates in pickers can't be nil. In order to create the picker, you have to have some sort of date in the binding, aka it can't be optional. The only other alternative I can think of would be to initialize the birthday as nil, and pass another variable into the picker where `.onChange` it updates the birthday. I think either solution is messy, WDYT?

2020-08-17 23:00 UTC, rickpasetto commented on TidepoolServiceKitUI/Views/PrescriptionCodeEntryView.swift
> +    @State private var didTapOnPicker: Bool = false
Could you do something like this?

```swift
    private var birthdayPicker: some View {
        let binding = Binding<Date>(
            get: {
                // Default to 35 years ago for birthdays, which is what the Apple Health app does
                self.birthday ?? Calendar.current.date(byAdding: .year, value: -35, to: Date())!
            },
            set: {
                self.birthday = $0
            })
        return ExpandableDatePicker(
            with: binding,
            pickerRange: viewModel.validDateRange,
            placeholderText: viewModel.placeholderFieldText
...
```
?

2020-08-17 23:08 UTC, novalegra commented on TidepoolServiceKitUI/Views/PrescriptionCodeEntryView.swift
> +    @State private var didTapOnPicker: Bool = false
Thanks - that's what I was looking to do :)

2020-08-17 23:32 UTC, novalegra commented on TidepoolServiceKitUI/Views/PrescriptionCodeEntryView.swift
> +    @State private var didTapOnPicker: Bool = false
Hmm, it works for every case, except when the user taps the picker to open it & taps it to close w/o changing any date in the picker (because then the binding isn't set). I'll find a fix

2020-08-18 00:59 UTC, rickpasetto requested changes
Sorry I'm super-confused now.  I thought you got rid of the `userDidTap` param on the picker, and you were going to using a "shim" binding (like I [commented on](https://github.com/tidepool-org/TidepoolService/pull/42#discussion_r471819770)).  Am I seeing the right code?

2020-08-18 00:59 UTC, rickpasetto commented on TidepoolServiceKitUI/View Models/PrescriptionReviewViewModel.swift
> +    let pickerStartDate = Calendar.current.date(byAdding: .year, value: -35, to: Date())!
Now I'm super-confused.  This doesn't appear to be used?  What am I missing?

2020-08-18 00:59 UTC, rickpasetto commented on TidepoolServiceKitUI/Views/PrescriptionCodeEntryView.swift
> +            userDidTap: $didTapOnPicker
I thought you were getting rid of this?

2020-08-18 00:59 UTC, rickpasetto commented on TidepoolServiceKitUI/Views/PrescriptionCodeEntryView.swift
> +    private var birthdayPicker: some View {
I thought you were going to use the `Binding` temp var I proposed?

2020-08-18 14:50 UTC, novalegra commented on TidepoolServiceKitUI/Views/PrescriptionCodeEntryView.swift
> +            userDidTap: $didTapOnPicker
OK, something didn't update properly when I pushed. I definitely removed it...

2020-08-18 14:53 UTC, novalegra commented on TidepoolServiceKitUI/Views/PrescriptionCodeEntryView.swift
> +            userDidTap: $didTapOnPicker
Ugh, I stashed to go to another branch and didn't push. Super sorry about that.

2020-08-18 16:51 UTC, novalegra commented on TidepoolServiceKitUI/Views/PrescriptionCodeEntryView.swift
> +    private var birthdayPicker: some View {
(see comment above, it was a stashing issue...)

2020-08-18 19:36 UTC, rickpasetto approved these changes
LGTM!

2020-08-18 19:38 UTC, merged