LOOP-1114: calls /info API to do a version check
tidepool-org/TidepoolService pull request #62
Opened 2021-09-10 22:31 UTC by rickpasetto

https://tidepool.atlassian.net/browse/LOOP-1114

2021-09-11 01:01 UTC, darinkrauss requested changes
See my comments and requested changes in LoopKit.

2021-09-11 01:01 UTC, darinkrauss commented on TidepoolServiceKit/TidepoolService.swift
> +        tapi.getInfo(environment: nil) { result in
[nit] Since the default is `nil`, just leave environment parameter off.

2021-09-11 01:01 UTC, darinkrauss commented on TidepoolServiceKit/TidepoolService.swift
> +    public func checkVersion(currentVersion: String, completion: @escaping (Result<VersionUpdate, Error>) -> Void) {
See my comment in related LoopKit PR about the `bundleIdentifier` parameter and checking against hard-coded Tidepool Loop bundle identifier.

2021-09-14 19:36 UTC, darinkrauss approved these changes
A couple of nits, but otherwise LGTM!

2021-09-14 19:36 UTC, darinkrauss commented on TidepoolServiceKit/LoopVersionInfo.swift
> +    public func getVersionUpdateNeeded(currentVersion version: String) -> VersionUpdate {
[nit] Why not just add this functionality as a local extension to `TInfo.Versions.Loop`?

2021-09-14 19:36 UTC, darinkrauss commented on TidepoolServiceKitTests/SemanticVersionTests.swift
> +        XCTAssertNil(SemanticVersion("-1.2.3.4"))
[nit] Is this going to assert while trying to run the unit tests?

2021-09-15 20:26 UTC, rickpasetto commented on TidepoolServiceKit/LoopVersionInfo.swift
> +    public func getVersionUpdateNeeded(currentVersion version: String) -> VersionUpdate {
I was viewing `TInfo` as policy-free, but `TidepoolService` as having the policy for this.

2021-09-15 20:29 UTC, rickpasetto commented on TidepoolServiceKitTests/SemanticVersionTests.swift
> +        XCTAssertNil(SemanticVersion("-1.2.3.4"))
Nope, because it won't match the regex

2021-09-15 20:35 UTC, darinkrauss commented on TidepoolServiceKit/LoopVersionInfo.swift
> +    public func getVersionUpdateNeeded(currentVersion version: String) -> VersionUpdate {
Right, but that doesn't mean you can't extend `TInfo` privately for the `TidepoolService`, right?

2021-09-15 20:36 UTC, darinkrauss commented on TidepoolServiceKitTests/SemanticVersionTests.swift
> +        XCTAssertNil(SemanticVersion("-1.2.3.4"))
Ah, then why the `assert(major >= 0)`s?

2021-09-15 21:11 UTC, rickpasetto commented on TidepoolServiceKit/LoopVersionInfo.swift
> +    public func getVersionUpdateNeeded(currentVersion version: String) -> VersionUpdate {
ok

2021-09-15 21:36 UTC, rickpasetto commented on TidepoolServiceKitTests/SemanticVersionTests.swift
> +        XCTAssertNil(SemanticVersion("-1.2.3.4"))
In case someone changes the regex

2021-09-15 22:12 UTC, darinkrauss approved these changes
LGTM! Thanks for making those changes.

2021-09-15 23:50 UTC, merged